"use client"

import Link from "next/link"
import { useCallback, useEffect, useState } from "react"
import { useParams, useRouter } from "next/navigation"
import { ArrowLeft, CheckCircle2, MessageSquareText, PhoneCall, Plus, ShieldCheck, UserRound } from "lucide-react"
import { toast } from "sonner"
import api from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { DisciplineLoading, SeverityBadge, StatusBadge, WorkflowStrip, formatDisciplineDate } from "@/components/discipline/discipline-ui"

type Row = Record<string, any>
type Detail = { incident:Row; witnesses:Row[]; evidence:Row[]; responses:Row[]; actions:Row[]; communications:Row[]; history:Row[]; permissions:{canReview:boolean} }
const actionTypes=["Verbal warning","Written warning","Counselling","Apology","Reflection note","Cleaning duty","Campus service","Mentor meeting","Behaviour improvement plan","Phone restriction","Recreation restriction","Parent call","Parent meeting","Final warning","Hostel restriction","Temporary suspension","Discipline committee review","Removal from hostel","Removal from institution"]

export default function IncidentDetailPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [data,setData]=useState<Detail|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false)
 const [review,setReview]=useState({decision:"approve",severity:"minor",discipline_marks:"0",note:""}); const [response,setResponse]=useState({response_type:"accepted",explanation:"",witness_details:""}); const [action,setAction]=useState({action_type:actionTypes[0],instructions:"",due_date:""}); const [contact,setContact]=useState({status:"called",method:"Phone",notes:""})
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get(`/discipline/incidents/${id}`);setData(r.data);setReview(x=>({...x,severity:r.data.incident.severity,discipline_marks:String(r.data.incident.discipline_marks)}))}catch(e:any){toast.error(e.response?.data?.error||"Could not load incident")}finally{setLoading(false)}},[id])
 useEffect(()=>{load()},[load]); const mutate=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);try{await fn();toast.success(message);await load()}catch(e:any){toast.error(e.response?.data?.error||"Action failed")}finally{setBusy(false)}}
 if(loading)return <DisciplineLoading label="Loading incident details"/>; if(!data)return <main className="p-8 text-sm text-red-600">Incident could not be loaded.</main>; const i=data.incident
 return <main className="mx-auto max-w-[1450px] space-y-5 p-4 md:p-8">
  <header className="flex flex-col gap-4 border-b pb-5 lg:flex-row lg:items-end lg:justify-between"><div className="flex gap-3"><Button variant="ghost" size="icon" onClick={()=>router.back()}><ArrowLeft className="h-5 w-5"/></Button><div><div className="flex flex-wrap gap-2"><b className="text-xs uppercase text-red-600">{i.reference_no}</b><SeverityBadge severity={i.severity}/><StatusBadge status={i.status}/></div><h1 className="mt-2 text-2xl font-bold">{i.student_name}</h1><p className="text-sm text-slate-500">{i.student_id} - {i.offence_name} - {formatDisciplineDate(i.reported_at,true)}</p></div></div><Button asChild variant="outline"><Link href={`/admin/disciplinary/students/${i.student_id}`}><UserRound className="mr-2 h-4 w-4"/>Student profile</Link></Button></header>
  <WorkflowStrip status={i.status}/>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(350px,.8fr)]"><div className="space-y-5">
   <Card title="Incident facts"><dl className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><Fact label="Problem" value={`${i.category_name} / ${i.offence_name}`}/><Fact label="Reported by" value={i.reporter_name}/><Fact label="Location" value={i.location}/><Fact label="Class" value={[i.class_name,i.division].filter(Boolean).join(" - ")}/><Fact label="Hostel / room" value={[i.hostel,i.floor,i.room_number].filter(Boolean).join(" / ")}/><Fact label="Marks" value={i.discipline_marks}/></dl><div className="mt-5 rounded-lg bg-slate-50 p-4 text-sm"><b className="text-xs uppercase text-slate-500">What happened</b><p className="mt-2 whitespace-pre-wrap">{i.short_description}</p></div>{i.immediate_action&&<Note tone="amber" label="Immediate action" value={i.immediate_action}/>} {i.private_staff_notes&&<Note tone="violet" label="Private staff note" value={i.private_staff_notes}/>}</Card>
   <Card title="Student explanation">{data.responses.map(x=><div key={x.id} className="mb-3 rounded-lg border p-4 text-sm"><div className="flex justify-between"><b className="capitalize">{x.response_type}</b><span className="text-xs text-slate-500">{formatDisciplineDate(x.created_at,true)}</span></div><p className="mt-2 whitespace-pre-wrap">{x.explanation}</p></div>)}{!data.responses.length&&<Empty text="No student explanation recorded."/>}{data.permissions.canReview&&<div className="mt-4 grid gap-3"><select className="control" value={response.response_type} onChange={e=>setResponse({...response,response_type:e.target.value})}><option value="accepted">Accepted</option><option value="denied">Denied</option></select><Textarea rows={4} value={response.explanation} onChange={e=>setResponse({...response,explanation:e.target.value})} placeholder="Student explanation"/><Input value={response.witness_details} onChange={e=>setResponse({...response,witness_details:e.target.value})} placeholder="Witness details (optional)"/><Button variant="outline" disabled={busy||!response.explanation.trim()} onClick={()=>mutate(()=>api.post(`/discipline/incidents/${id}/student-response`,response),"Explanation recorded")}><MessageSquareText className="mr-2 h-4 w-4"/>Save explanation</Button></div>}</Card>
   <Card title="Corrective actions">{data.actions.map(x=><div key={x.id} className="mb-3 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{x.action_type}</b><p className="text-xs text-slate-500">Due {formatDisciplineDate(x.due_date)}</p></div><select value={x.status} disabled={!data.permissions.canReview||busy} onChange={e=>mutate(()=>api.patch(`/discipline/actions/${x.id}`,{status:e.target.value,note:`Status changed to ${e.target.value}`}),"Action updated")} className="h-9 rounded-md border px-2 text-xs">{["not_started","in_progress","completed","overdue","cancelled"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></div>{x.instructions&&<p className="mt-2 text-sm">{x.instructions}</p>}</div>)}{!data.actions.length&&<Empty text="No corrective action assigned."/>}{data.permissions.canReview&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={action.action_type} onChange={e=>setAction({...action,action_type:e.target.value})} className="control">{actionTypes.map(v=><option key={v}>{v}</option>)}</select><Input type="date" value={action.due_date} onChange={e=>setAction({...action,due_date:e.target.value})}/><Textarea className="sm:col-span-2" rows={3} value={action.instructions} onChange={e=>setAction({...action,instructions:e.target.value})} placeholder="Instructions and expected outcome"/><Button className="sm:col-span-2" variant="outline" disabled={busy} onClick={()=>mutate(()=>api.post(`/discipline/incidents/${id}/actions`,action),"Corrective action assigned")}><Plus className="mr-2 h-4 w-4"/>Assign action</Button></div>}</Card>
  </div><aside className="space-y-5">
   {data.permissions.canReview&&<Card title="Review decision"><div className="grid gap-3"><select value={review.decision} onChange={e=>setReview({...review,decision:e.target.value})} className="control"><option value="approve">Approve report</option><option value="request_explanation">Request explanation</option><option value="escalate">Escalate</option><option value="cancel">Cancel report</option></select><div className="grid grid-cols-2 gap-3"><select value={review.severity} onChange={e=>setReview({...review,severity:e.target.value})} className="control">{["minor","moderate","major","critical"].map(v=><option key={v}>{v}</option>)}</select><Input type="number" min={0} max={100} value={review.discipline_marks} onChange={e=>setReview({...review,discipline_marks:e.target.value})}/></div><Textarea rows={3} value={review.note} onChange={e=>setReview({...review,note:e.target.value})} placeholder="Review note"/><Button disabled={busy} onClick={()=>mutate(()=>api.post(`/discipline/incidents/${id}/review`,{...review,discipline_marks:Number(review.discipline_marks)}),"Review saved")}><ShieldCheck className="mr-2 h-4 w-4"/>Save decision</Button></div></Card>}
   <Card title="Parent communication"><div className="flex justify-between text-sm"><span>Current status</span><b className="capitalize text-blue-700">{i.parent_notification_status.replaceAll("_"," ")}</b></div>{data.communications.map(x=><div key={x.id} className="mt-3 rounded-lg border p-3 text-sm"><div className="flex justify-between"><b className="capitalize">{x.status.replaceAll("_"," ")}</b><span className="text-xs text-slate-500">{formatDisciplineDate(x.contacted_at,true)}</span></div>{x.notes&&<p className="mt-1">{x.notes}</p>}</div>)}{data.permissions.canReview&&<div className="mt-4 grid gap-3"><select value={contact.status} onChange={e=>setContact({...contact,status:e.target.value})} className="control">{["pending","message_sent","called","meeting_scheduled","acknowledged"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select><Input value={contact.method} onChange={e=>setContact({...contact,method:e.target.value})}/><Textarea rows={3} value={contact.notes} onChange={e=>setContact({...contact,notes:e.target.value})} placeholder="Communication notes"/><Button variant="outline" disabled={busy} onClick={()=>mutate(()=>api.post(`/discipline/incidents/${id}/parent-communications`,contact),"Parent contact recorded")}><PhoneCall className="mr-2 h-4 w-4"/>Record contact</Button></div>}</Card>
   <Card title="Case timeline"><div className="space-y-4 border-l pl-4">{data.history.map(x=><div key={x.id}><b className="text-sm capitalize">{x.to_status.replaceAll("_"," ")}</b><p className="text-xs text-slate-500">{formatDisciplineDate(x.created_at,true)}{x.changed_by_name?` - ${x.changed_by_name}`:""}</p>{x.note&&<p className="text-xs">{x.note}</p>}</div>)}</div></Card>
   {data.permissions.canReview&&!['completed','cancelled'].includes(i.status)&&<Button className="w-full bg-emerald-600 hover:bg-emerald-700" disabled={busy} onClick={()=>mutate(()=>api.post(`/discipline/incidents/${id}/close`,{note:"Case reviewed and closed"}),"Case closed")}><CheckCircle2 className="mr-2 h-4 w-4"/>Close case</Button>}
  </aside></div>
 </main>
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border bg-white p-5"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>}
function Fact({label,value}:{label:string;value:unknown}){return <div><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1 font-medium">{String(value||"-")}</dd></div>}
function Note({tone,label,value}:{tone:"amber"|"violet";label:string;value:string}){return <div className={`mt-3 rounded-lg border p-4 text-sm ${tone==='amber'?'border-amber-100 bg-amber-50':'border-violet-100 bg-violet-50'}`}><b>{label}:</b> {value}</div>}
function Empty({text}:{text:string}){return <p className="text-sm text-slate-500">{text}</p>}