"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { ArrowLeft, FileText, Link2, Save, Search, Send, UserRound, Users } from "lucide-react"
import { toast } from "sonner"
import api from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

interface Student { adm_no: string; name: string; standard?: string; division?: string; photo_url?: string | null }
interface Offence { id: string; name: string; default_severity: string; default_marks: number; is_quick_report: boolean; parent_notification_default: boolean }
interface Category { id: string; name: string; offences: Offence[] }

const initialForm = { student_id:"",category_id:"",offence_type_id:"",severity:"minor",discipline_marks:1,reported_at:new Date().toISOString().slice(0,16),location:"",hostel:"",floor:"",room_number:"",short_description:"",immediate_action:"",student_position:"not_recorded",parent_notification_required:false,private_staff_notes:"",witness_name:"",witness_details:"",evidence_url:"" }

export default function NewDisciplineIncidentPage(){
    const router=useRouter(); const [mode,setMode]=useState<"quick"|"detailed">("quick"); const [form,setForm]=useState(initialForm); const [categories,setCategories]=useState<Category[]>([]); const [students,setStudents]=useState<Student[]>([]); const [studentSearch,setStudentSearch]=useState(""); const [loadingStudents,setLoadingStudents]=useState(false); const [saving,setSaving]=useState(false)
    const selectedCategory=categories.find(item=>item.id===form.category_id); const offences=selectedCategory?.offences || []; const selectedOffence=offences.find(item=>item.id===form.offence_type_id)
    const set=(key:string,value:unknown)=>setForm(current=>({...current,[key]:value}))
    useEffect(()=>{api.get("/discipline/settings").then(response=>setCategories(response.data.categories||[])).catch(()=>toast.error("Could not load discipline categories"))},[])
    useEffect(()=>{const timer=setTimeout(()=>{if(studentSearch.trim().length<2){setStudents([]);return}setLoadingStudents(true);api.get("/students",{params:{light:true,status:"active",search:studentSearch.trim(),limit:12,offset:0,count:false}}).then(response=>setStudents(response.data.students||[])).finally(()=>setLoadingStudents(false))},250);return()=>clearTimeout(timer)},[studentSearch])
    useEffect(()=>{if(!selectedOffence)return;setForm(current=>({...current,severity:selectedOffence.default_severity,discipline_marks:selectedOffence.default_marks,parent_notification_required:selectedOffence.parent_notification_default}))},[selectedOffence])
    const selectedStudent=useMemo(()=>students.find(item=>item.adm_no===form.student_id),[students,form.student_id])
    const submit=async(draft:boolean)=>{if(!form.student_id||!form.category_id||!form.offence_type_id||!form.short_description.trim()){toast.error("Select a student and problem, then add a description");return}setSaving(true);try{const payload={...form,save_as_draft:draft,idempotency_key:crypto.randomUUID(),witnesses:form.witness_name?[{name:form.witness_name,details:form.witness_details}]:[],evidence:form.evidence_url?[{file_name:"Evidence link",file_url:form.evidence_url,visibility:"staff_only"}]:[]};const response=await api.post("/discipline/incidents",payload);toast.success(draft?"Draft saved":"Incident submitted for review");router.push(`/admin/disciplinary/incidents/${response.data.incident.id}`)}catch(error:any){toast.error(error.response?.data?.error||"Could not save incident")}finally{setSaving(false)}}
    return <main className="mx-auto max-w-5xl space-y-5 p-4 md:p-8"><header className="flex items-start gap-3 border-b border-slate-200 pb-5"><Button variant="ghost" size="icon" onClick={()=>router.back()} aria-label="Go back"><ArrowLeft className="h-5 w-5" /></Button><div><p className="text-xs font-bold uppercase text-red-600">Discipline management</p><h1 className="text-2xl font-bold text-slate-950">Report an Incident</h1><p className="text-sm text-slate-500">Record facts clearly. Marks are applied only after authorized review.</p></div></header>
    <div className="grid grid-cols-2 rounded-lg bg-slate-100 p-1"><button onClick={()=>setMode("quick")} className={`rounded-md px-4 py-2 text-sm font-semibold ${mode==="quick"?"bg-white text-slate-950 shadow-sm":"text-slate-500"}`}>Quick report</button><button onClick={()=>setMode("detailed")} className={`rounded-md px-4 py-2 text-sm font-semibold ${mode==="detailed"?"bg-white text-slate-950 shadow-sm":"text-slate-500"}`}>Detailed report</button></div>
    <section className="rounded-lg border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><UserRound className="h-5 w-5 text-blue-600"/><h2 className="font-semibold text-slate-950">Student and incident</h2></div><div className="grid gap-4 md:grid-cols-2"><label className="relative block md:col-span-2"><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Find student</span><Search className="absolute bottom-3 left-3 h-4 w-4 text-slate-400"/><Input value={studentSearch} onChange={event=>setStudentSearch(event.target.value)} placeholder="Search by name or admission number" className="pl-9"/></label>{(loadingStudents||students.length>0)&&!selectedStudent&&<div className="max-h-56 overflow-y-auto rounded-lg border md:col-span-2">{loadingStudents?<p className="p-4 text-sm text-slate-500">Searching...</p>:students.map(student=><button key={student.adm_no} onClick={()=>set("student_id",student.adm_no)} className="flex w-full items-center justify-between border-b px-4 py-3 text-left last:border-0 hover:bg-slate-50"><span><strong className="block text-sm text-slate-900">{student.name}</strong><span className="text-xs text-slate-500">{student.adm_no} · {[student.standard,student.division].filter(Boolean).join(" - ")||"Not placed"}</span></span></button>)}</div>}{selectedStudent&&<div className="flex items-center justify-between rounded-lg border border-blue-200 bg-blue-50 p-4 md:col-span-2"><div><p className="font-semibold text-slate-950">{selectedStudent.name}</p><p className="text-sm text-slate-500">{selectedStudent.adm_no} · {[selectedStudent.standard,selectedStudent.division].filter(Boolean).join(" - ")||"Current placement"}</p></div><Button variant="ghost" size="sm" onClick={()=>{set("student_id","");setStudentSearch("");setStudents([])}}>Change</Button></div>}
    <label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Problem category</span><select value={form.category_id} onChange={event=>{setForm(current=>({...current,category_id:event.target.value,offence_type_id:""}))}} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm"><option value="">Select category</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Specific problem</span><select value={form.offence_type_id} onChange={event=>set("offence_type_id",event.target.value)} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm"><option value="">Select problem</option>{offences.filter(item=>mode==="detailed"||item.is_quick_report).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Date and time</span><Input type="datetime-local" value={form.reported_at} onChange={event=>set("reported_at",event.target.value)}/></label><label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Location</span><Input value={form.location} onChange={event=>set("location",event.target.value)} placeholder="Classroom, hostel, campus..."/></label><label className="md:col-span-2"><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">What happened?</span><Textarea value={form.short_description} onChange={event=>set("short_description",event.target.value)} placeholder="Record observable facts, people involved, and immediate context." rows={5}/></label></div></section>
    <section className="rounded-lg border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><FileText className="h-5 w-5 text-amber-600"/><h2 className="font-semibold text-slate-950">Initial assessment</h2></div><div className="grid gap-4 md:grid-cols-3"><label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Severity</span><select value={form.severity} onChange={event=>set("severity",event.target.value)} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm">{["minor","moderate","major","critical"].map(value=><option key={value}>{value}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Proposed marks</span><Input type="number" min={0} max={100} value={form.discipline_marks} onChange={event=>set("discipline_marks",Number(event.target.value))}/></label><label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Student position</span><select value={form.student_position} onChange={event=>set("student_position",event.target.value)} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm"><option value="not_recorded">Not recorded</option><option value="accepted">Accepted</option><option value="denied">Denied</option></select></label><label className="md:col-span-3"><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Immediate action taken</span><Textarea value={form.immediate_action} onChange={event=>set("immediate_action",event.target.value)} rows={3} placeholder="Separation, verbal direction, safety action..."/></label><label className="flex items-center gap-3 rounded-lg border p-3 md:col-span-3"><input type="checkbox" checked={form.parent_notification_required} onChange={event=>set("parent_notification_required",event.target.checked)} className="h-4 w-4"/><span><strong className="block text-sm">Parent notification required</strong><span className="text-xs text-slate-500">Reviewers can track calls, messages, meetings, and acknowledgement.</span></span></label></div></section>
    {mode==="detailed"&&<section className="rounded-lg border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><Users className="h-5 w-5 text-violet-600"/><h2 className="font-semibold text-slate-950">Evidence and internal context</h2></div><div className="grid gap-4 md:grid-cols-2"><label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Witness name</span><Input value={form.witness_name} onChange={event=>set("witness_name",event.target.value)} /></label><label><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Witness details</span><Input value={form.witness_details} onChange={event=>set("witness_details",event.target.value)} /></label><label className="md:col-span-2"><span className="mb-1.5 flex items-center gap-2 text-xs font-bold uppercase text-slate-500"><Link2 className="h-3.5 w-3.5"/>Evidence link</span><Input value={form.evidence_url} onChange={event=>set("evidence_url",event.target.value)} placeholder="Private photo, document, or video URL"/></label><label className="md:col-span-2"><span className="mb-1.5 block text-xs font-bold uppercase text-slate-500">Private staff notes</span><Textarea value={form.private_staff_notes} onChange={event=>set("private_staff_notes",event.target.value)} rows={4} placeholder="Visible only to authorized discipline reviewers."/></label></div></section>}
    <footer className="sticky bottom-0 flex flex-col-reverse gap-2 border-t bg-white/95 py-4 backdrop-blur sm:flex-row sm:justify-end"><Button variant="outline" disabled={saving} onClick={()=>submit(true)}><Save className="mr-2 h-4 w-4"/>Save draft</Button><Button disabled={saving} onClick={()=>submit(false)} className="bg-red-600 hover:bg-red-700"><Send className="mr-2 h-4 w-4"/>{saving?"Saving...":"Submit for review"}</Button></footer></main>
}