"use client"
import Link from "next/link"
import { useCallback,useEffect,useMemo,useState } from "react"
import { useParams } from "next/navigation"
import { Award,Clock3,FileWarning,ShieldCheck,TrendingDown,UserRound } from "lucide-react"
import { toast } from "sonner"
import api from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { DisciplineLoading,DisciplineMetric,RiskBadge,SeverityBadge,StatusBadge,formatDisciplineDate } from "@/components/discipline/discipline-ui"

type Row=Record<string,any>; type Profile={student:Row;incidents:Row[];actions:Row[];positiveMarks:Row[];summary:{activeMarks:number;positiveMarks:number;riskLevel:string}}
export default function StudentDisciplineProfile(){const {id}=useParams<{id:string}>();const [data,setData]=useState<Profile|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [award,setAward]=useState({category:"Clear improvement",marks:1,note:""})
 const load=useCallback(()=>{setLoading(true);api.get(`/discipline/students/${id}/profile`).then(r=>setData(r.data)).catch((e:any)=>toast.error(e.response?.data?.error||"Could not load profile")).finally(()=>setLoading(false))},[id]);useEffect(()=>load(),[load]);const computed=useMemo(()=>{const month=new Date().toISOString().slice(0,7);const recent=(data?.incidents||[]).filter(x=>String(x.reported_at).slice(0,7)===month).length;const pending=(data?.actions||[]).filter(x=>!["completed","cancelled"].includes(x.status)).length;const earlier=(data?.incidents||[]).filter(x=>new Date(x.reported_at)<new Date(Date.now()-30*86400000)).length;const trend=recent===0&&earlier>0?"Improving":recent>Math.max(earlier,1)?"Worsening":"Stable";return{recent,pending,trend}},[data]);if(loading)return <DisciplineLoading label="Loading student discipline profile"/>;if(!data)return <main className="p-8">Student not found.</main>
 const addAward=async()=>{setSaving(true);try{await api.post(`/discipline/students/${id}/positive-behaviour`,award);toast.success("Positive behaviour recorded");setAward({...award,note:""});load()}catch(e:any){toast.error(e.response?.data?.error||"Could not save award")}finally{setSaving(false)}}
 return <main className="mx-auto max-w-[1450px] space-y-5 p-4 md:p-8"><header className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-blue-50 text-blue-700"><UserRound/></div><div><p className="text-xs font-bold uppercase text-red-600">Student discipline profile</p><h1 className="text-2xl font-bold">{data.student.name}</h1><p className="text-sm text-slate-500">{data.student.adm_no} - {[data.student.standard,data.student.division].filter(Boolean).join(" - ")||"Not placed"}</p></div></div><Button asChild variant="outline"><Link href={`/admin/disciplinary/new?student=${id}`}>Report incident</Link></Button></header>
 <section className="grid grid-cols-2 gap-3 lg:grid-cols-6"><DisciplineMetric label="Active marks" value={data.summary.activeMarks} icon={FileWarning} tone="red"/><DisciplineMetric label="Positive marks" value={data.summary.positiveMarks} icon={Award} tone="emerald"/><DisciplineMetric label="All incidents" value={data.incidents.length} icon={FileWarning}/><DisciplineMetric label="This month" value={computed.recent} icon={Clock3} tone="amber"/><DisciplineMetric label="Pending actions" value={computed.pending} icon={Clock3} tone="violet"/><div className="rounded-lg border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">Current standing</p><div className="mt-5"><RiskBadge level={data.summary.riskLevel}/><p className="mt-2 flex items-center gap-1 text-sm text-slate-500"><TrendingDown className="h-4 w-4"/>{computed.trend}</p></div></div></section>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(340px,.6fr)]"><section className="overflow-hidden rounded-lg border bg-white"><div className="border-b p-5"><h2 className="font-semibold">Full discipline timeline</h2><p className="text-sm text-slate-500">History is retained even after marks expire.</p></div><div className="divide-y">{data.incidents.map(x=><Link href={`/admin/disciplinary/incidents/${x.id}`} key={x.id} className="grid gap-3 p-4 hover:bg-slate-50 sm:grid-cols-[1fr_auto_auto]"><div><b>{x.offence_name}</b><p className="text-xs text-slate-500">{x.reference_no} - {x.category_name} - {formatDisciplineDate(x.reported_at,true)}</p></div><SeverityBadge severity={x.severity}/><StatusBadge status={x.status}/></Link>)}{!data.incidents.length&&<p className="p-10 text-center text-sm text-slate-500">No discipline incidents recorded.</p>}</div></section>
 <aside className="space-y-5"><section className="rounded-lg border bg-white p-5"><div className="flex items-center gap-2"><Award className="h-5 w-5 text-emerald-600"/><h2 className="font-semibold">Recognize improvement</h2></div><div className="mt-4 grid gap-3"><select className="h-10 rounded-md border px-3 text-sm" value={award.category} onChange={e=>setAward({...award,category:e.target.value})}>{["Good manners","Clean room","Helping others","Punctuality","Leadership","Completing corrective work","Following campus rules","Clear improvement"].map(v=><option key={v}>{v}</option>)}</select><Input type="number" min={1} max={100} value={award.marks} onChange={e=>setAward({...award,marks:Number(e.target.value)})}/><Textarea rows={3} value={award.note} onChange={e=>setAward({...award,note:e.target.value})} placeholder="What improvement was observed?"/><Button className="bg-emerald-600 hover:bg-emerald-700" disabled={saving} onClick={addAward}><ShieldCheck className="mr-2 h-4 w-4"/>Award positive marks</Button></div></section><section className="rounded-lg border bg-white p-5"><h2 className="font-semibold">Positive behaviour history</h2><div className="mt-3 space-y-3">{data.positiveMarks.map(x=><div key={x.id} className="rounded-lg bg-emerald-50 p-3 text-sm"><div className="flex justify-between"><b>{x.category}</b><strong className="text-emerald-700">+{x.marks}</strong></div><p className="mt-1 text-xs text-slate-500">{formatDisciplineDate(x.awarded_at,true)}</p>{x.note&&<p className="mt-1">{x.note}</p>}</div>)}{!data.positiveMarks.length&&<p className="text-sm text-slate-500">No positive marks yet.</p>}</div></section></aside></div></main>}